[tasks.pack]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.serve]
install_crate = { crate_name = "https", binary = "httplz", test_arg = "--help" }
command = "httplz"
dependencies = ["pack"]