[package]
name = 'space_game'
version = '0.1.0'
edition = '2021'

[dependencies]
space_game_core = { path = '../space_game_core' }

nalgebra = { version = "0.30.1", features = ["bytemuck"] }
once_cell = '1'
bytemuck = '1'
anyhow = {version = '1', features = ['backtrace'] }
thiserror = '1'
indexmap = '1'
log = '0.4'
