[package]
name = "space_game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1"
log = "0.4"
console_log = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
glam = "0.20"
futures = "0.3"
space_game_core = { path = "../space_game_core" }

[dependencies.web-sys]
version = "0.3"
features = [
  'BinaryType',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'HtmlImageElement',
  'WebGlBuffer',
  'WebGlVertexArrayObject',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlActiveInfo',
  'WebGlShader',
  'WebGlTexture',
  'WebGlUniformLocation',  
  'WebSocket',
  'Window',
]
